parser: babel-eslint
parserOptions:
  ecmaFeatures:
    jsx: true
    experimentalObjectRestSpread: true
extends: airbnb
rules:
  arrow-body-style: off
  arrow-parens:
    - error
    - always
  function-paren-newline: off
  class-methods-use-this: off
  no-case-declarations: off
  global-require: off
  react/jsx-curly-spacing:
    - error
    - always
  react/forbid-prop-types: off
  react/prefer-stateless-function: off
  jsx-a11y/media-has-caption: off
  import/no-extraneous-dependencies: [error, { devDependencies: true }]
  import/prefer-default-export: off
env:
  browser: true
  mocha: true
  node: true
